# Generated by Django 4.0.5 on 2022-06-11 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('symbol', models.CharField(default='AAPL', max_length=4, primary_key=True, serialize=False, unique=True)),
                ('cur_price', models.FloatField()),
                ('industry', models.CharField(choices=[('LGOODS', 'Luxury Goods'), ('APPS', 'Software - Application'), ('BIOTECH', 'Biotechnology')], default='BIOTECH', max_length=40)),
                ('daily_high', models.FloatField()),
                ('daily_low', models.FloatField()),
                ('overseas', models.BooleanField(default=False)),
            ],
        ),
    ]
